line.bot:
  channel-token: 'WvXnjRDtFc74akSBEZc1c6Je6o/eJXznHr/nxRqMu7w7wwxz12w3rOgOOSkcqqVMSI8isAISw9yzwUpPywglE0qIodKKaSJn99JEWcp7AFWHtig8yNoGWZ5ZUrzSIClLGDKFtO7OHDksnh5VDARJOQdB04t89/1O/w1cDnyilFU='
  channel-secret: 'ae4a4681db0ef031602b7ad05d761dc9'
  handler.path: /callback
