line.bot:
  channel-token: '8tI/dPG3GjEqNI1WpLSgPE8ClgcC+36k7mx/xKJqNvDwKuH6u6T0wMbpLDRyd+iV7A3NqYaVhEZ42RjUvD6O53/PX7B0R9tUJd8VFTN1aXpM9iR9YLsOnnaEGsyyGUNZuEINrOcVmjLV1RSVOg6cTwdB04t89/1O/w1cDnyilFU='
  channel-secret: '14f14234a323f914426190c51a9dcb42'
  handler.path: /callback
